### ISSUE TITLE
[Bug]: Encountering timeout error from the SMTP server after few minutes.

### ISSUE THREAD

**Issue by jeeban101** [jeeban101/AI-Enabled-Candidate-Resume-Screening-#1]
While running the program, the SMTP server works fine for few minutes but after a while it shows smtp server timeout
Can anyone help me with that

**Comment by rohit-gupta3** [comment]
Is this the error you are talking about

![image](https://github.com/jeeban101/AI-Enabled-Candidate-Resume-Screening-/assets/82712515/576e6aa6-4300-4a9d-bc07-43422cfd49e9)

**Comment by jeeban101** [comment]
Yes, I'm referring to this error.
